# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

filterRemovalTimeout: 300000

embedDeletionEmoji: '🗑️'

projects:
  - BDS
  - MC
  - MCCE
  - MCD
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  invalidTicketEmoji: ⏸
  noLinkEmoji: ⛔
  warningLifetime: 5000
  waitingEmoji: ⌛

  invalidRequestJql: created > -24h

  suggestedEmoji:
    - ✅
    - ☑️
    - ❌
    - 💬
    - 📁

  ignorePrependResponseMessageEmoji: ✅
  ignoreResolutionEmoji: 💬
  bulkEmoji: 📁

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}

    ```
