# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCD
  - MCE
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  noLinkEmoji: ⛔
  noLinkWarningLifetime: 5000
  waitingEmoji: ⌛

  suggestedEmoji:
    - ✅
    - ☑️
    - ❌
    - 💬
  
  ignorePrependResponseMessageEmoji: ✅
  ignoreResolutionEmoji: 💬

  normalNotificationsRole: 'Normal Request Notifications'
  someNotificationsRole: 'Special Request Notifications'
  oldNotificationsRole: 'Three Day Old Request Notifications'
  oldNotificationsTimeDifference: 259200000 # 3 days
  longNotificationsRole: 'One Week Old Request Notifications'
  longNotificationsTimeDifference: 604800000 # 1 week

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}
    
    ```
